// Error reading included file Templates/GUIForms/Templates/Licenses/license-default.txt
package Interficie;


import java.util.Calendar;
import classes.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.beans.Introspector;
import java.beans.PropertyDescriptor;
import static java.lang.String.valueOf;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumnModel;
import java.util.Date;




/**
 *
 * @author javi
 */


public class GUI extends javax.swing.JFrame {
   Xml XML =new Xml();
   int plaça=0;
   int index;
   int[] arrayPlaça;
        

   
   
    /**
     * Creates new form GUI
     */
    
    public GUI() {
        initComponents();
        inici();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_menu = new javax.swing.JPanel();
        jButton_inici = new javax.swing.JButton();
        jButton_afegir = new javax.swing.JButton();
        Entrada_Surtida = new javax.swing.JButton();
        jButton_mostrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton_tanca = new javax.swing.JButton();
        jLayeredPane = new javax.swing.JLayeredPane();
        panel_inici = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_mostrar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_mostrar = new javax.swing.JTable();
        panel_afegir = new javax.swing.JPanel();
        panel_afegir.setBounds(0, 0, 600, 600);
        jLabel_nom1 = new javax.swing.JLabel();
        jLabel_tipus = new javax.swing.JLabel();
        jLabel_marca = new javax.swing.JLabel();
        jLabel_model = new javax.swing.JLabel();
        jLabel_color = new javax.swing.JLabel();
        jLabel_plasa = new javax.swing.JLabel();
        jLabel_matricula = new javax.swing.JLabel();
        jTextField_nom = new javax.swing.JTextField();
        jTextField_cognom = new javax.swing.JTextField();
        jTextField_model = new javax.swing.JTextField();
        jTextField_color = new javax.swing.JTextField();
        jTextField_plaça = new javax.swing.JTextField();
        jTextField_hora = new javax.swing.JTextField();
        jLabel_cognom1 = new javax.swing.JLabel();
        jComboBox_tipus = new javax.swing.JComboBox();
        jComboBox_marca = new javax.swing.JComboBox();
        jLabel_plasa1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_plasa2 = new javax.swing.JLabel();
        jTextField_matricula = new javax.swing.JTextField();
        jTextField_preu = new javax.swing.JTextField();
        panel_sortida = new javax.swing.JPanel();
        panel_afegir.setBounds(0, 0, 600, 600);
        jLabel_marca1 = new javax.swing.JLabel();
        jLabel_model1 = new javax.swing.JLabel();
        jLabel_color1 = new javax.swing.JLabel();
        jLabel_plasa3 = new javax.swing.JLabel();
        jLabel_matricula1 = new javax.swing.JLabel();
        jTextField_marcaSortida = new javax.swing.JTextField();
        jTextField_modelSortida = new javax.swing.JTextField();
        jTextField_horaEntrada = new javax.swing.JTextField();
        jComboBox_matriculaSortida = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel_plasa5 = new javax.swing.JLabel();
        jTextField_pagar = new javax.swing.JTextField();
        jTextField_preuSortida = new javax.swing.JTextField();
        jLabel_plasa6 = new javax.swing.JLabel();
        jTextField_horaSortida = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_nomSortida = new javax.swing.JTextField();
        jTextField_cognomSortida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tempsFinal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(980, 510));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_menu.setMinimumSize(new java.awt.Dimension(700, 40));
        jPanel_menu.setName(""); // NOI18N
        jPanel_menu.setPreferredSize(new java.awt.Dimension(700, 40));

        jButton_inici.setText("Inici");
        jButton_inici.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_iniciMouseClicked(evt);
            }
        });
        jButton_inici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_iniciActionPerformed(evt);
            }
        });
        jPanel_menu.add(jButton_inici);

        jButton_afegir.setText("Entrada");
        jButton_afegir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_afegirMouseClicked(evt);
            }
        });
        jButton_afegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_afegirActionPerformed(evt);
            }
        });
        jPanel_menu.add(jButton_afegir);

        Entrada_Surtida.setText("Sortida");
        Entrada_Surtida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Entrada_SurtidaMouseClicked(evt);
            }
        });
        Entrada_Surtida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrada_SurtidaActionPerformed(evt);
            }
        });
        jPanel_menu.add(Entrada_Surtida);

        jButton_mostrar.setText("Mostrar");
        jButton_mostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_mostrarMouseClicked(evt);
            }
        });
        jButton_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_mostrarActionPerformed(evt);
            }
        });
        jPanel_menu.add(jButton_mostrar);

        jButton1.setText("Documentació XML");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel_menu.add(jButton1);

        jButton_tanca.setText("Tanca");
        jButton_tanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_tancaMouseClicked(evt);
            }
        });
        jButton_tanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tancaActionPerformed(evt);
            }
        });
        jPanel_menu.add(jButton_tanca);

        getContentPane().add(jPanel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLayeredPane.setMinimumSize(new java.awt.Dimension(980, 450));
        jLayeredPane.setName(""); // NOI18N
        jLayeredPane.setLayout(new java.awt.CardLayout());

        panel_inici.setPreferredSize(new java.awt.Dimension(950, 400));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("Parking XupiWay");
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout panel_iniciLayout = new javax.swing.GroupLayout(panel_inici);
        panel_inici.setLayout(panel_iniciLayout);
        panel_iniciLayout.setHorizontalGroup(
            panel_iniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_iniciLayout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(231, 231, 231))
        );
        panel_iniciLayout.setVerticalGroup(
            panel_iniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_iniciLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jLayeredPane.add(panel_inici, "card2");

        panel_mostrar.setAutoscrolls(true);
        panel_mostrar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        panel_mostrar.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panel_mostrar.setMinimumSize(new java.awt.Dimension(985, 405));
        panel_mostrar.setName(""); // NOI18N
        panel_mostrar.setOpaque(false);
        panel_mostrar.setPreferredSize(new java.awt.Dimension(970, 500));
        panel_mostrar.setRequestFocusEnabled(false);
        panel_mostrar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panel_mostrarFocusGained(evt);
            }
        });

        jScrollPane2.setMinimumSize(new java.awt.Dimension(950, 400));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(950, 400));

        jTable_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Cognoms", "Tipus", "Matrícula", "Marca", "Model", "Color", "Plaça", "Preu", "Hora Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_mostrar.setMinimumSize(new java.awt.Dimension(900, 400));
        jTable_mostrar.setName(""); // NOI18N
        jTable_mostrar.setOpaque(false);
        jTable_mostrar.setPreferredSize(new java.awt.Dimension(910, 480));
        jTable_mostrar.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(jTable_mostrar);

        javax.swing.GroupLayout panel_mostrarLayout = new javax.swing.GroupLayout(panel_mostrar);
        panel_mostrar.setLayout(panel_mostrarLayout);
        panel_mostrarLayout.setHorizontalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mostrarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panel_mostrarLayout.setVerticalGroup(
            panel_mostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mostrarLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLayeredPane.add(panel_mostrar, "card3");

        panel_afegir.setMinimumSize(new java.awt.Dimension(950, 400));
        panel_afegir.setPreferredSize(new java.awt.Dimension(950, 400));
        panel_afegir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_nom1.setText("Cognoms:");
        panel_afegir.add(jLabel_nom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 80, 20));

        jLabel_tipus.setText("Tipus de vehicle:");
        panel_afegir.add(jLabel_tipus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel_marca.setText("Marca:");
        panel_afegir.add(jLabel_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jLabel_model.setText("Model:");
        panel_afegir.add(jLabel_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, -1, -1));

        jLabel_color.setText("Color:");
        panel_afegir.add(jLabel_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel_plasa.setText("Preu/hora");
        panel_afegir.add(jLabel_plasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 100, 30));

        jLabel_matricula.setText("Matrícula:");
        panel_afegir.add(jLabel_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        jTextField_nom.setEditable(false);
        jTextField_nom.setNextFocusableComponent(jTextField_cognom);
        jTextField_nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_nomFocusLost(evt);
            }
        });
        jTextField_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, 30));

        jTextField_cognom.setEditable(false);
        jTextField_cognom.setNextFocusableComponent(jComboBox_tipus);
        jTextField_cognom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_cognomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_cognomFocusLost(evt);
            }
        });
        jTextField_cognom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cognomActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_cognom, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 150, 30));

        jTextField_model.setEditable(false);
        jTextField_model.setNextFocusableComponent(jTextField_color);
        jTextField_model.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_modelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_modelFocusLost(evt);
            }
        });
        jTextField_model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_modelActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 166, 30));

        jTextField_color.setEditable(false);
        jTextField_color.setNextFocusableComponent(jTextField_matricula);
        jTextField_color.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_colorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_colorFocusLost(evt);
            }
        });
        jTextField_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_colorActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 118, 30));

        jTextField_plaça.setEditable(false);
        jTextField_plaça.setToolTipText("");
        jTextField_plaça.setEnabled(false);
        jTextField_plaça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_plaçaActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_plaça, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 98, 30));

        jTextField_hora.setEditable(false);
        jTextField_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_horaActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 130, 30));

        jLabel_cognom1.setText("Nom:");
        panel_afegir.add(jLabel_cognom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jComboBox_tipus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Cotxe", "Moto" }));
        jComboBox_tipus.setNextFocusableComponent(jComboBox_marca);
        jComboBox_tipus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipusActionPerformed(evt);
            }
        });
        panel_afegir.add(jComboBox_tipus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 71, 30));

        jComboBox_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Alfa Romeo", "Aprilia", "Aston Martin", "Audi", "BMW", "Christler", "Chevrolet", "Derbi", "Ducati", "Ferrari", "Fiat", "Ford", "Gilera", "Harley-Davison", "Honda", "Hyundai", "Infinity", "Jaguar", "Jeep", "Kawasaki", "Kia", "Kimco", "KTM", "Lancia", "Land Rover", "Lexus", "Mazda", "Mercedes", "Mini", "Mitsubishi", "Nissan", "Opel", "Peogeot", "Porsche", "Renault", "Seat", "Skoda", "Smart", "Subaru", "Suzuki", "Tata", "Toyota", "Subaru", "Volkswagen", "Volvo", "Yamaha" }));
        jComboBox_marca.setNextFocusableComponent(jTextField_model);
        jComboBox_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_marcaActionPerformed(evt);
            }
        });
        panel_afegir.add(jComboBox_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 110, -1));

        jLabel_plasa1.setText("Plaça:");
        panel_afegir.add(jLabel_plasa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, -1));

        jButton2.setText("Afegir");
        jButton2.setNextFocusableComponent(jTextField_nom);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_afegir.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 94, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("ENTRADA DE VEHICLE AL PARKING");
        jLabel2.setPreferredSize(new java.awt.Dimension(230, 18));
        jLabel2.setRequestFocusEnabled(false);
        panel_afegir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 490, 30));

        jLabel_plasa2.setText("Hora entrada:");
        panel_afegir.add(jLabel_plasa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 120, 20));

        jTextField_matricula.setEditable(false);
        jTextField_matricula.setNextFocusableComponent(jButton2);
        jTextField_matricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_matriculaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_matriculaFocusLost(evt);
            }
        });
        jTextField_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_matriculaActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 160, 30));

        jTextField_preu.setText("2");
        jTextField_preu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_preuActionPerformed(evt);
            }
        });
        panel_afegir.add(jTextField_preu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 100, 30));

        jLayeredPane.add(panel_afegir, "card4");

        panel_sortida.setMinimumSize(new java.awt.Dimension(950, 400));
        panel_sortida.setPreferredSize(new java.awt.Dimension(950, 400));
        panel_sortida.setLayout(null);

        jLabel_marca1.setText("Matricula:");
        panel_sortida.add(jLabel_marca1);
        jLabel_marca1.setBounds(40, 60, 100, 15);

        jLabel_model1.setText("Marca:");
        panel_sortida.add(jLabel_model1);
        jLabel_model1.setBounds(310, 60, 100, 15);

        jLabel_color1.setText("Model:");
        panel_sortida.add(jLabel_color1);
        jLabel_color1.setBounds(580, 60, 70, 15);

        jLabel_plasa3.setText("Preu/hora:");
        panel_sortida.add(jLabel_plasa3);
        jLabel_plasa3.setBounds(580, 190, 120, 30);

        jLabel_matricula1.setText("Total a Pagar:");
        panel_sortida.add(jLabel_matricula1);
        jLabel_matricula1.setBounds(590, 300, 130, 15);

        jTextField_marcaSortida.setEditable(false);
        jTextField_marcaSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_marcaSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_marcaSortida);
        jTextField_marcaSortida.setBounds(310, 80, 120, 30);

        jTextField_modelSortida.setEditable(false);
        jTextField_modelSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_modelSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_modelSortida);
        jTextField_modelSortida.setBounds(580, 80, 118, 30);

        jTextField_horaEntrada.setEditable(false);
        jTextField_horaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_horaEntradaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_horaEntrada);
        jTextField_horaEntrada.setBounds(40, 150, 120, 34);

        jComboBox_matriculaSortida.setToolTipText("");
        jComboBox_matriculaSortida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox_matriculaSortidaFocusGained(evt);
            }
        });
        jComboBox_matriculaSortida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_matriculaSortidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox_matriculaSortidaMouseEntered(evt);
            }
        });
        jComboBox_matriculaSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_matriculaSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jComboBox_matriculaSortida);
        jComboBox_matriculaSortida.setBounds(40, 80, 110, 24);

        jButton3.setText("Pagat");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_sortida.add(jButton3);
        jButton3.setBounds(40, 340, 94, 25);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("SORTIDA DEL PARKING");
        jLabel3.setPreferredSize(new java.awt.Dimension(230, 18));
        jLabel3.setRequestFocusEnabled(false);
        panel_sortida.add(jLabel3);
        jLabel3.setBounds(70, 20, 309, 29);

        jLabel_plasa5.setText("Hora entrada:");
        panel_sortida.add(jLabel_plasa5);
        jLabel_plasa5.setBounds(40, 120, 120, 30);

        jTextField_pagar.setEditable(false);
        jTextField_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pagarActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_pagar);
        jTextField_pagar.setBounds(590, 330, 166, 30);

        jTextField_preuSortida.setEditable(false);
        jTextField_preuSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_preuSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_preuSortida);
        jTextField_preuSortida.setBounds(580, 220, 100, 30);

        jLabel_plasa6.setText("Hora sortida:");
        panel_sortida.add(jLabel_plasa6);
        jLabel_plasa6.setBounds(40, 200, 120, 20);

        jTextField_horaSortida.setEditable(false);
        jTextField_horaSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_horaSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_horaSortida);
        jTextField_horaSortida.setBounds(40, 220, 120, 34);

        jButton4.setText("Calcular");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panel_sortida.add(jButton4);
        jButton4.setBounds(40, 290, 94, 25);

        jLabel4.setText("Nom:");
        panel_sortida.add(jLabel4);
        jLabel4.setBounds(310, 130, 36, 15);

        jLabel5.setText("Cognom:");
        panel_sortida.add(jLabel5);
        jLabel5.setBounds(580, 120, 62, 20);

        jTextField_nomSortida.setEditable(false);
        jTextField_nomSortida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nomSortidaActionPerformed(evt);
            }
        });
        panel_sortida.add(jTextField_nomSortida);
        jTextField_nomSortida.setBounds(310, 150, 120, 30);

        jTextField_cognomSortida.setEditable(false);
        panel_sortida.add(jTextField_cognomSortida);
        jTextField_cognomSortida.setBounds(580, 150, 270, 30);

        jLabel6.setText("Temps al parking");
        panel_sortida.add(jLabel6);
        jLabel6.setBounds(310, 300, 140, 15);

        tempsFinal.setEditable(false);
        panel_sortida.add(tempsFinal);
        tempsFinal.setBounds(310, 330, 140, 30);
        panel_sortida.add(jSeparator1);
        jSeparator1.setBounds(310, 270, 590, 10);

        jLayeredPane.add(panel_sortida, "card4");

        getContentPane().add(jLayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, -1, -1));
        jLayeredPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void inici(){
        panel_inici.setVisible(true);
        panel_mostrar.setVisible(false);
        panel_afegir.setVisible(false);
        InOut.llegir("vehicles.dat");
         arrayPlaça = new int[100];
        
        for (int i=0;i<arrayPlaça.length;i++){
                arrayPlaça[i]=-1;
            }
        for (int i=0;i<Array.arrayParking.size();i++){       
        arrayPlaça[Array.arrayParking.get(i).getPlasa()-1]=Array.arrayParking.get(i).getPlasa();
        }
}
        
   
    private void jButton_iniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_iniciActionPerformed

    }//GEN-LAST:event_jButton_iniciActionPerformed

    private void jButton_iniciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_iniciMouseClicked
        // TODO add your handling code here:
        //Fem visible el jpanel principal
        panel_inici.setVisible(true);
        panel_mostrar.setVisible(false);
        panel_afegir.setVisible(false);
        panel_sortida.setVisible(false);

    }//GEN-LAST:event_jButton_iniciMouseClicked

    private void jButton_afegirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_afegirMouseClicked
        // TODO add your handling code here:
            panel_inici.setVisible(false);
            panel_mostrar.setVisible(false);
            panel_afegir.setVisible(true);
            panel_sortida.setVisible(false);

            //Contingut dels botons del menú afegir:
            
            jTextField_nom.setText("Fulanito");
            jTextField_cognom.setText("De Tal");
            jComboBox_tipus.setSelectedIndex(0);
            jComboBox_marca.setSelectedIndex(0);
            jTextField_model.setText("Picaso, Cordoba,...");
            jTextField_color.setText("Gris, Negre, Blau,...");
            jTextField_plaça.setText("Auto");
            jTextField_matricula.setText("XXXX-XXX");

                java.util.Date date = new java.util.Date();
                java.text.SimpleDateFormat hour=new java.text.SimpleDateFormat("HH:mm:ss");
            jTextField_hora.setText(hour.format(date)); 
            
            

    }//GEN-LAST:event_jButton_afegirMouseClicked

    private void jButton_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_mostrarActionPerformed
        // TODO add your handling code here:

        

//La primer columna passa a mostrar-se en 2n lloc
        //cm.removeColumn(cm.getColumn(2));
    }//GEN-LAST:event_jButton_mostrarActionPerformed

    private void jButton_mostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_mostrarMouseClicked
        // TODO add your handling code here:
                ModelTaula<Vehicle> mt = new ModelTaula(new String[]{"Cognoms", "Color", "Hora Entrada",
            "Marca", "Matricula", "Model", "Nom", "Plaça", "Preu", "Tipus"}, Array.arrayParking);
       
        jTable_mostrar.setModel(mt);
                //Si volem canviar l'ordre de visualització de les columnes, borra-les, etc...
        TableColumnModel cm=jTable_mostrar.getColumnModel();
        cm.moveColumn(6, 0);
        cm.moveColumn(9, 2);
        cm.moveColumn(5, 3);
        cm.moveColumn(7, 4);
        cm.moveColumn(7, 3);
        
        panel_inici.setVisible(false);
        //Fem visible el jpanel principal
        panel_mostrar.setVisible(true);
        panel_afegir.setVisible(false);
        panel_sortida.setVisible(false);

        
    }//GEN-LAST:event_jButton_mostrarMouseClicked

    private void jButton_afegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_afegirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_afegirActionPerformed

    private void jTextField_cognomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cognomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cognomActionPerformed

    private void jTextField_modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_modelActionPerformed

    private void jTextField_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_colorActionPerformed

    private void jTextField_plaçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_plaçaActionPerformed
        // TODO add your handling code here:
  
    }//GEN-LAST:event_jTextField_plaçaActionPerformed

    private void jTextField_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_horaActionPerformed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_jTextField_horaActionPerformed

    private void jComboBox_tipusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipusActionPerformed

    private void jComboBox_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_marcaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Xml.xml();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
      //Preparem el rellotge:
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat hour=new java.text.SimpleDateFormat("HH:mm:ss");
        //Guardem el temps en una variable per a que sigui fixa.        
        String horaInicial=(hour.format(date)).toString();        
        
//Assignem la plaça buscant un forat a la Array abans d'assignali la última posició.

            int j=0;
             for (j=0;j<arrayPlaça.length;j++){
                if(arrayPlaça[j]==-1){arrayPlaça[j]=j+1;
                break;}
            }
                
      plaça=arrayPlaça[j];
         
            JOptionPane.showMessageDialog(null, "Al usuari se li ha assignat la plaça: "+plaça);
        

        Array.arrayParking.add(new Vehicle(jTextField_nom.getText(), jTextField_cognom.getText(), jComboBox_tipus.getSelectedItem().toString(), jTextField_matricula.getText(), jComboBox_marca.getSelectedItem().toString(), jTextField_model.getText(), jTextField_color.getText(), 
                                      (plaça),Float.parseFloat(jTextField_preu.getText()), horaInicial));
        
        
            //Resetejem els camps de text.
            jTextField_nom.setText("Fulanito...");
            jTextField_cognom.setText("De Tal...");
            jComboBox_tipus.setSelectedIndex(0);
            jComboBox_marca.setSelectedIndex(0);
            jTextField_model.setText("Picaso, cordoba,....");
            jTextField_color.setText("Gris, Negre, Blau,...");
            jTextField_plaça.setText("Auto");
            jTextField_matricula.setText("XXXX-XXX");
            //Possem l'hora actual.
            jTextField_hora.setText(hour.format(date));


            		
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_matriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_matriculaActionPerformed

    private void jTextField_preuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_preuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_preuActionPerformed

    private void jButton_tancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tancaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_tancaActionPerformed

    private void jButton_tancaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_tancaMouseClicked
        // TODO add your handling code here:
        InOut.escriure("vehicles.dat");
        this.dispose();
    }//GEN-LAST:event_jButton_tancaMouseClicked

    private void jTextField_horaSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_horaSortidaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_horaSortidaActionPerformed

    private void jTextField_preuSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_preuSortidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_preuSortidaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
for (index=0;jComboBox_matriculaSortida.getSelectedItem()!=Array.arrayParking.get(index).getMatricula();index++){
        }
jComboBox_matriculaSortida.removeItem(jComboBox_matriculaSortida.getSelectedItem());

        arrayPlaça[Array.arrayParking.get(index).getPlasa()]=-1;
        Array.arrayParking.remove(index);

        JOptionPane.showMessageDialog(null, "Transacció finalitzada\nVehicle eliminat correctament.");
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat hour=new java.text.SimpleDateFormat("HH:mm:ss");
        jTextField_horaSortida.setText(hour.format(date)); 
        

      
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox_matriculaSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_matriculaSortidaActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_matriculaSortidaActionPerformed

    private void jTextField_horaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_horaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_horaEntradaActionPerformed

    private void jTextField_modelSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_modelSortidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_modelSortidaActionPerformed

    private void jTextField_marcaSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_marcaSortidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_marcaSortidaActionPerformed

    private void jTextField_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_pagarActionPerformed

    private void panel_mostrarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panel_mostrarFocusGained
        // TODO add your handling code here:
     
         
    }//GEN-LAST:event_panel_mostrarFocusGained

    private void Entrada_SurtidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entrada_SurtidaMouseClicked
        panel_inici.setVisible(false);
        //Fem visible el jpanel principal
        panel_mostrar.setVisible(false);
        panel_afegir.setVisible(false);
        panel_sortida.setVisible(true);
        //Possem l'hora actual a la casella
        java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat hour=new java.text.SimpleDateFormat("HH:mm:ss");
        jTextField_horaSortida.setText(hour.format(date)); 
        

        try{
           
        jComboBox_matriculaSortida.removeAllItems();
        }catch(Exception e){
        System.out.println(e);
        }
        
        String matricula;
        for(int i=0;i<Array.arrayParking.size();i++){
        matricula=Array.arrayParking.get(i).getMatricula();
        jComboBox_matriculaSortida.addItem(matricula);
        }
        for (index=0;jComboBox_matriculaSortida.getSelectedItem()!=Array.arrayParking.get(index).getMatricula();index++){
        }
                
        jTextField_marcaSortida.setText(Array.arrayParking.get(index).getMarca());
        jTextField_modelSortida.setText(Array.arrayParking.get(index).getModel());
        jTextField_nomSortida.setText(Array.arrayParking.get(index).getNom());
        jTextField_cognomSortida.setText(Array.arrayParking.get(index).getCognom());
        jTextField_horaEntrada.setText(Array.arrayParking.get(index).getHoraEntrada());
        jTextField_preuSortida.setText(Float.toString(Array.arrayParking.get(index).getPreu()));
    }//GEN-LAST:event_Entrada_SurtidaMouseClicked

    private void Entrada_SurtidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrada_SurtidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Entrada_SurtidaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField_colorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_colorFocusGained
        // TODO add your handling code here:
                jTextField_color.setText("");
        jTextField_color.setEditable(true);
    }//GEN-LAST:event_jTextField_colorFocusGained

    private void jTextField_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField_nomActionPerformed

    private void jTextField_nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nomFocusGained
        // TODO add your handling code here:
        jTextField_nom.setText("");
        jTextField_nom.setEditable(true);
    }//GEN-LAST:event_jTextField_nomFocusGained

    private void jTextField_nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_nomFocusLost
        // TODO add your handling code here:
String texto = jTextField_nom.getText();
if ("".equals(texto)) jTextField_nom.setText("Fulanito");
    }//GEN-LAST:event_jTextField_nomFocusLost

    private void jTextField_cognomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_cognomFocusGained
        // TODO add your handling code here:
                jTextField_cognom.setText("");
        jTextField_cognom.setEditable(true);
    }//GEN-LAST:event_jTextField_cognomFocusGained

    private void jTextField_modelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_modelFocusGained
        // TODO add your handling code here:
                jTextField_model.setText("");
        jTextField_model.setEditable(true);
    }//GEN-LAST:event_jTextField_modelFocusGained

    private void jTextField_matriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_matriculaFocusGained
        // TODO add your handling code here:
                jTextField_matricula.setText("");
        jTextField_matricula.setEditable(true);
    }//GEN-LAST:event_jTextField_matriculaFocusGained

    private void jTextField_cognomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_cognomFocusLost
        // TODO add your handling code here:
        String texto = jTextField_cognom.getText();
if ("".equals(texto)) jTextField_cognom.setText("De Tal");
    }//GEN-LAST:event_jTextField_cognomFocusLost

    private void jTextField_modelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_modelFocusLost
        // TODO add your handling code here:
        String texto = jTextField_model.getText();
if ("".equals(texto)) jTextField_model.setText("Picaso, Cordoba,...");
    }//GEN-LAST:event_jTextField_modelFocusLost

    private void jTextField_colorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_colorFocusLost
        // TODO add your handling code here:
                String texto = jTextField_color.getText();
if ("".equals(texto)) jTextField_color.setText("Negre, Blau,...");
    }//GEN-LAST:event_jTextField_colorFocusLost

    private void jTextField_matriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_matriculaFocusLost
        // TODO add your handling code here:
    String texto = jTextField_matricula.getText();
    if ("".equals(texto)) jTextField_matricula.setText("XXXX-XXX");
    }//GEN-LAST:event_jTextField_matriculaFocusLost

    private void jTextField_nomSortidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nomSortidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nomSortidaActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
                 java.util.Date date = new java.util.Date();
        java.text.SimpleDateFormat hour=new java.text.SimpleDateFormat("HH:mm:ss");
        jTextField_horaSortida.setText(hour.format(date));
  
        String horafinal=(hour.format(date)).toString();
        String horaInicial=Array.arrayParking.get(index).getHoraEntrada();
        String[] tempsF = horafinal.split(":");
        String[] tempsI = horaInicial.split(":");
       // for(int i=0;i<tempsF.length;i++){
       // System.out.println("en la posició "+i+" hi ha "+tempsF[i]);
       // }
        double horaF= Integer.parseInt(tempsF[0]) - Integer.parseInt(tempsI[0]);
        int minutsF= Integer.parseInt(tempsF[1]) - Integer.parseInt(tempsI[1]);
        if(minutsF<0)minutsF=minutsF*-1;
        int segonsF= Integer.parseInt(tempsF[2]) - Integer.parseInt(tempsI[2]);
        if(segonsF<0)segonsF=segonsF*-1;
        tempsFinal.setText((int)horaF+":"+minutsF+":"+segonsF);
        double mig=0.5;
        
        if(minutsF<=30)horaF=horaF+mig;
        if(minutsF>30)horaF=horaF+1;
        System.out.print(mig+" "+horaF+"\n");
        jTextField_pagar.setText(horaF * Array.arrayParking.get(index).getPreu()+"€");
             
    }//GEN-LAST:event_jButton4MouseClicked

    private void jComboBox_matriculaSortidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_matriculaSortidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_matriculaSortidaMouseClicked

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseEntered

    private void jComboBox_matriculaSortidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_matriculaSortidaMouseEntered
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jComboBox_matriculaSortidaMouseEntered

    private void jComboBox_matriculaSortidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox_matriculaSortidaFocusGained
        // TODO add your handling code here:
 for (index=0;jComboBox_matriculaSortida.getSelectedItem()!=Array.arrayParking.get(index).getMatricula();index++){
        }
        jTextField_marcaSortida.setText(Array.arrayParking.get(index).getMarca());
        jTextField_modelSortida.setText(Array.arrayParking.get(index).getModel());
        jTextField_nomSortida.setText(Array.arrayParking.get(index).getNom());
        jTextField_cognomSortida.setText(Array.arrayParking.get(index).getCognom());
        jTextField_horaEntrada.setText(Array.arrayParking.get(index).getHoraEntrada());
        jTextField_preuSortida.setText(Float.toString(Array.arrayParking.get(index).getPreu()));    
    }//GEN-LAST:event_jComboBox_matriculaSortidaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrada_Surtida;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_afegir;
    private javax.swing.JButton jButton_inici;
    private javax.swing.JButton jButton_mostrar;
    private javax.swing.JButton jButton_tanca;
    private javax.swing.JComboBox jComboBox_marca;
    private javax.swing.JComboBox jComboBox_matriculaSortida;
    private javax.swing.JComboBox jComboBox_tipus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_cognom1;
    private javax.swing.JLabel jLabel_color;
    private javax.swing.JLabel jLabel_color1;
    private javax.swing.JLabel jLabel_marca;
    private javax.swing.JLabel jLabel_marca1;
    private javax.swing.JLabel jLabel_matricula;
    private javax.swing.JLabel jLabel_matricula1;
    private javax.swing.JLabel jLabel_model;
    private javax.swing.JLabel jLabel_model1;
    private javax.swing.JLabel jLabel_nom1;
    private javax.swing.JLabel jLabel_plasa;
    private javax.swing.JLabel jLabel_plasa1;
    private javax.swing.JLabel jLabel_plasa2;
    private javax.swing.JLabel jLabel_plasa3;
    private javax.swing.JLabel jLabel_plasa5;
    private javax.swing.JLabel jLabel_plasa6;
    private javax.swing.JLabel jLabel_tipus;
    private javax.swing.JLayeredPane jLayeredPane;
    private javax.swing.JPanel jPanel_menu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable_mostrar;
    private javax.swing.JTextField jTextField_cognom;
    private javax.swing.JTextField jTextField_cognomSortida;
    private javax.swing.JTextField jTextField_color;
    private javax.swing.JTextField jTextField_hora;
    private javax.swing.JTextField jTextField_horaEntrada;
    private javax.swing.JTextField jTextField_horaSortida;
    private javax.swing.JTextField jTextField_marcaSortida;
    private javax.swing.JTextField jTextField_matricula;
    private javax.swing.JTextField jTextField_model;
    private javax.swing.JTextField jTextField_modelSortida;
    private javax.swing.JTextField jTextField_nom;
    private javax.swing.JTextField jTextField_nomSortida;
    private javax.swing.JTextField jTextField_pagar;
    private javax.swing.JTextField jTextField_plaça;
    private javax.swing.JTextField jTextField_preu;
    private javax.swing.JTextField jTextField_preuSortida;
    private javax.swing.JPanel panel_afegir;
    private javax.swing.JPanel panel_inici;
    private javax.swing.JPanel panel_mostrar;
    private javax.swing.JPanel panel_sortida;
    private javax.swing.JTextField tempsFinal;
    // End of variables declaration//GEN-END:variables

}


class ModelTaula<T> extends AbstractTableModel {

    private String[] columnNames;
    private List<T> dades;

    public ModelTaula(String[] nomColumnes, ArrayList<T> dades) {
        this.columnNames = nomColumnes;
        this.dades = dades;
    }

    //Necessari per a que mostre el nom de les columnes passat al crear l'objecte
    @Override
    public String getColumnName(int column) {
        return columnNames[column];
    }
    
    //Necessari per a que mostre el número correcte de files de dades
    @Override
    public int getRowCount() {
        int cont=0;
        
        if(dades!=null) cont=dades.size();
        
        return cont;
    }

    //Necessari per a que mostre el número correcte de columnes 
    @Override
    public int getColumnCount() {
        
        int cont=0;
        
        if(columnNames!=null) cont=columnNames.length;
        
        return cont;
    }

    //Necessari per a que mostre les dades passades al crear l'objecte
    @Override
    public Object getValueAt(int rowIndex, int columnIndex) {

        Class<?> classe = dades.get(0).getClass();
        //Anotem el nº de camps de la classe
        int ncamps = classe.getDeclaredFields().length;

        Method[] methods = new Method[ncamps];
        int i = 0;
        try {
            for (PropertyDescriptor pD : Introspector.getBeanInfo(classe).getPropertyDescriptors()) {
                Method m = pD.getReadMethod();
                if (m != null & !m.getName().equals("getClass")) {
                    methods[i++] = m;
                }
            }
        } catch (java.beans.IntrospectionException ex) {
            //Logger.getLogger(ModelTaula.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            return methods[columnIndex].invoke(dades.get(rowIndex));
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(ModelTaula.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;

    }
}